#%RAML 1.0 Trait
responses:
    400:
      body:
        application/json:
          type: object
          example: |
            {
              "message": "Bad Request"
            }
    401:
      body:
        application/json:
          type: object
          example: |
            {
              "message": "Unauthorised"
            }